### ISSUE TITLE
[2022-11-25] 네이버 검색광고 API 접속 도메인 변경 정식 서비스(12/22) 안내

### ISSUE THREAD

**Issue by daisy-de** [Soomgo-Platform/soomgo-gather#23]
[2022-11-25] 네이버 검색광고 API 접속 도메인 변경 정식 서비스(12/22) 안내
안녕하십니까 네이버 검색광고 API 담당자입니다.

지난 22년 9월 20일 공지 드린 네이버 검색광고 API 서비스 도메인 변경 작업과 관련하여
변경 도메인(api.searchad.naver.com)에 대한 BETA 테스트 종료 및 정식 서비스를 시작하게 되어 이에 공지를 드립니다.

변경 내역
현재 도메인 : api.naver.com
변경도메인 : api.searchad.naver.com

변경 일정 (모든 시간 KST 기준)
api.naver.com 도메인 서비스 중단 : 2023년 3월 22일 ,일정 변경시 별도 공지
api.searchad.naver.com 도메인 서비스 베타 테스트 시작 : 2022년 9월 21일 오후 중
api.searchad.naver.com 도메인 서비스 베타 테스트 종료 : 2022년 12월 22일 오후 중
api.searchad.naver.com 도메인 정식 서비스 시작 : 2022년 12월 22일 오후 중

api.naver.com 도메인은 서비스 중단 시점인 2023년 3월까지는 계속 사용하실수 있으며 서비스 중단 시점 이후에는 사용하실 수 없습니다.
감사합니다.

**Comment by rohawolf** [comment]
수정된 버전 (2.1) 배포 완료
